name: Customization
version: '${project.version}'
main: xyz.lalivre.customization.Customization
api-version: 1.18
commands:
  death:
    description: Get player's last death location.
    usage: /<command> [player]
  waypoint:
    description: Manage waypoints to keep track of interesting locatio,s
    usage: /<command> [list|add|remove|[waypointName]] [waypointName]
